---
#docker-compose file for spring boot app with data access linked with mysql as db
version: '3'
services:
  mysql-db:
    image: sujipillai/mysql #custom mysql image with initialized database and tables
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=userapp
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
  main-app:
    build: .
    image: sujipillai/spring-boot-userapp
    depends_on:
      - mysql-db
    ports:
      - 8081:8081
    container_name: user-app
    volumes:
      - DataVolume1:/app/logs
volumes:
  mysql-data:
  DataVolume1: